### PR TITLE
Update resolvePageComponent helper to work with both glob and glogEager

### PR DESCRIPTION
**Pull request by Esirei**
This pull request updates the `resolvePageComponent` inertia helper to work with the object returned both by the glob and globEager imports.

### CODE REVIEW

**Comment by jessarcher** [comment]
Hi @Esirei, thanks for the PR!

Could you please explain the use case and benefit of this?

**Comment by Esirei** [comment]
> Hi @Esirei, thanks for the PR!
> 
> Could you please explain the use case and benefit of this?

Hello @jessarcher , unlike the glob import which compiles each page/component/js into separate files and requests them on demand (lazy loaded), the globEager import compiles all into a single app.js file. Of course this will have a slower initial website load, but faster page responses, it depends on the developer which tradeoff they want.

This PR updates the helper function to work with either technique, I just need to figure out how to tell typescript that the generic cannot be a function to fix the failed tests.

**Comment by jessarcher** [comment]
Thanks, @Esirei. That makes sense :+1:

**Comment by Esirei** [comment]
Hi @jessarcher, I finally had some time to get the issue out of the way, also added tests for the helper.

**Review by timacdonald — APPROVED** [review]

**Comment by jessarcher** [comment]
Thanks, @Esirei!

**Pull request merged**
