### PR TITLE
[0.7.x] Vite 4 support

### PR DESCRIPTION
**Pull request by timacdonald**

### CODE REVIEW

**Comment by xsjcTony** [comment]
Nice to see it's in progress!

**Comment by jessarcher** [comment]
I have tested this change with:

* [x] Laravel skeleton running Vite 3
* [x] Laravel skeleton running Vite 4
* [x] Breeze Blade with Vite 3
* [x] Breeze Blade with Vite 4
* [x] Breeze Vue + SSR with Vite 3
* [x] Breeze Vue + SSR with Vite 4
* [x] Breeze React + SSR with Vite 3
* [x] Breeze React + SSR with Vite 4

**Review by jessarcher — APPROVED** [review]

**Comment by rmirandasv** [comment]
Please merge this PR

**Comment by samehdoush** [comment]
When will it be added?
Very excited to try out the vite 4

**Pull request merged**
